// Every MarketplaceListing field EXCEPT buyerEmail, sellerEmail,
// stripeSessionId, easypostShipmentId, and shippingLabelUrl, which carry
// field-level auth (Admin/Seller/owner only — the label URL is a PDF with the
// buyer's address). Requesting them under apiKey returns a per-field "Not
// Authorized" error on every item, so public reads must select around them.
// Keep in sync with amplify/data/resource.ts.
export const MARKETPLACE_PUBLIC_FIELDS = [
  "id",
  "title",
  "subtitle",
  "description",
  "price",
  "condition",
  "category",
  "image",
  "images",
  "thumbImages",
  "mediumImages",
  "fullImages",
  "quantity",
  "acceptsOffers",
  "acceptedOfferAmount",
  "featured",
  "status",
  "sold",
  "buyerUserId",
  "paid",
  "paidAt",
  "chargeTax",
  "taxRate",
  "sellerUserId",
  "sellerDisplayName",
  "sellerPublicId",
  "shippingStatus",
  "trackingNumber",
  "carrier",
  "trackingUrl",
  "shippedAt",
  "deliveredAt",
  "buyerReceivedAt",
  "pendingBuyerSub",
  "lastOfferSmsAt",
  "createdAt",
  "updatedAt",
] as const;
