// Every MarketplaceListing field EXCEPT buyerEmail and sellerEmail, which carry
// field-level auth (Admin/Seller/owner only). Requesting them under apiKey
// returns a per-field "Not Authorized" error on every item, so public reads
// must select around them. Keep in sync with amplify/data/resource.ts.
export const MARKETPLACE_PUBLIC_FIELDS = [
  "id",
  "title",
  "subtitle",
  "description",
  "price",
  "condition",
  "category",
  "image",
  "images",
  "thumbImages",
  "mediumImages",
  "fullImages",
  "quantity",
  "acceptsOffers",
  "acceptedOfferAmount",
  "featured",
  "status",
  "sold",
  "buyerUserId",
  "paid",
  "paidAt",
  "stripeSessionId",
  "chargeTax",
  "taxRate",
  "sellerUserId",
  "sellerDisplayName",
  "sellerPublicId",
  "shippingStatus",
  "trackingNumber",
  "carrier",
  "trackingUrl",
  "shippedAt",
  "deliveredAt",
  "buyerReceivedAt",
  "pendingBuyerSub",
  "lastOfferSmsAt",
  "easypostShipmentId",
  "shippingLabelUrl",
  "createdAt",
  "updatedAt",
] as const;
